version: "3.8"

services:

  frontend:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - 3000:3000
      
  redis:
    image: "redis:alpine"

  trigger:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    command: ["python", "app/main.py"]
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    env_file:
      - ./backend/.env

  gemini_worker:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    command: ["python", "app/gemini/worker.py"]
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    scale: 1
    env_file:
      - ./backend/.env

  vector_worker:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    command: ["python", "app/vector/worker.py"]
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    env_file:
      - ./backend/.env